---
name: vizceral

releases:
  - name: vizceral
    version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: vizceral-app
  instances: 1
  azs: [z1]
  jobs:
    - name: vizceral
  vm_type: default
  stemcell: default
  networks:
    - name: default

update:
  canaries: 0
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
